unstable_features = true
version = "Two"
edition = "2018"
imports_indent = "Visual"
imports_layout = "Horizontal"
max_width = 120
comment_width = 100
error_on_line_overflow = true
condense_wildcard_suffixes = true
reorder_impl_items = true
use_field_init_shorthand = true
match_arm_blocks = true
match_block_trailing_comma = true
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
#use_small_heuristics = "Max"
#struct_lit_single_line = false
